<?php 
//$_items = $this->getReviewsCollection_By_Collection_Show();
$_items =$this->getReviewsCollection_By_Collection_Filter_By_Categories_Show();

?>
<?php $limit_length = 160;?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
        <h2><?php echo $this->__('Customer Reviews') ?></h2>
        <?php echo $this->getChildHtml('toolbar') ?>
        <ul>
        <?php foreach ($_items as $_review):?>
        <?php
        $_product = Mage::getModel('catalog/product')->load($_review['entity_pk_value']); 
        ?>
         <li>
          <span class="product-name"><?php echo $this->__('Product Name: ');?></span><a href="<?php echo $_product->getProductUrl() ?>" ><?php echo $_product->getName()?></a><br/>
             <span class="review-title"><?php echo $this->__('Review Title: ');?></span> <a href="<?php echo Mage::getUrl('review/product/list', array('id'=> $_product->getId()));?>"> <span class="review-title"><?php echo $this->htmlEscape($_review->getTitle()) ?></span> </a> <br/>
             <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?><br/>
         
                <!-- Review Detail -->
                <span><?php echo $this->__('Review Detail: ');?></span>
                <?php if (strlen($_review->getDetail()) >  $limit_length) : ?>
                 <?php echo trim($this->helper('recentreviewproducts/data')->cutText2($_review->getDetail(),$limit_length)) ?> <br/>
                <?php else: ?>
                 <?php echo trim($_review->getDetail()) ?> <br/>
                  <?php endif;?>
                <!-- End Review Detail -->
		
		<!--Review Post On -->
                <small class="date"><?php echo $this->__('Posted on : %s', $this->formatDate($_review->getCreatedAt()), 'long') ?></small><br/><br/>
		<!--End Review Post On -->
           </li>
        <?php endforeach; ?>
      </ul>
    <?php endif;?>
</div>