<?php
$post = $this->getPost();
$postUrl = Mage::getUrl('blog').$this->getLinkCat().$post->getIdentifier().'.html';
?>
<a href="http://www.facebook.com/sharer.php?u=<?php echo $postUrl ?>&title=<?php echo urlencode($post->getTitle()) ?>" target="_blank">
        <img border="0" src="http://3.bp.blogspot.com/_vLeiVavkV_M/SnleIlLdGwI/AAAAAAAABd8/RfHnWIGGMEY/s200/facebook.png" alt="Post item information on Facebook" title="Post item information on Facebook" />
</a>

<a href="http://twitter.com/home?status=Currently buying <?php echo $postUrl ?>" title="Click to send this product to Twitter!" target="_blank">
        <img border="0" src="http://www.cbc.ca/news/yourvoice/assets/images/yourvoice-twitter.png" alt="Add To Twiiter" title="Add To Twiiter">
</a>

<a title="Add To Del.icio.us" target="_blank" href="http://del.icio.us/post?url=<?php echo $postUrl ?>&amp;title=<?php echo urlencode($post->getTitle()) ?>">
        <img border="0" src="http://2.bp.blogspot.com/_vLeiVavkV_M/Snld35mPSDI/AAAAAAAABds/ccrOpOmP9Zk/s200/delicious.png" alt="Add To Del.icio.us" title="Add To Del.icio.us">
</a>

<a title="Stumble This" target="_blank" href="http://www.stumbleupon.com/refer.php?url=<?php echo $postUrl ?>&amp;title=<?php echo urlencode($post->getTitle()) ?>">
        <img border="0" src="http://2.bp.blogspot.com/_vLeiVavkV_M/SnleiulEMVI/AAAAAAAABeU/kO09nNTlQeo/s200/stumbleupon.png" alt="Stumble This" title="Stumble This">
</a>

<a title="Digg This" target="_blank" href="http://digg.com/submit?phase=2&amp;url=<?php echo $postUrl ?>&amp;title=<?php echo urlencode($post->getTitle()) ?>">
        <img border="0" src="http://3.bp.blogspot.com/_vLeiVavkV_M/Snld_x-wXoI/AAAAAAAABd0/cTsGU_Y-zQ8/s200/digg.png" alt="Digg This" title="Digg This">
</a>

<a title="Add To Reddit" target="_blank" href="http://reddit.com/submit?url=<?php echo $postUrl ?>&amp;title=<?php echo urlencode($post->getTitle()) ?>">
        <img border="0" src="http://3.bp.blogspot.com/_vLeiVavkV_M/SnleX1tMMtI/AAAAAAAABeM/gQSYdrmSc3k/s200/reddit.png" alt="Add To Reddit" title="Add To Reddit">
</a>

<a title="Add To Yahoo" target="_blank" href="http://myweb2.search.yahoo.com/myresults/bookmarklet?t=<?php echo $postUrl ?>&amp;title=<?php echo urlencode($post->getTitle()) ?>">
        <img border="0" src="http://1.bp.blogspot.com/_vLeiVavkV_M/SnlexsGX2QI/AAAAAAAABes/ai6zvzZKCgw/s200/yahoo.png" alt="Add To Yahoo" title="Add To Yahoo">
</a>