<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
	
	$conf = new EM_Em0057settings_Em0057settings();	
	$w 	= $conf->get_widget_width();
	$h 	= $conf->get_widget_height();	
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="home_deal_products">
   <div id="scrollbar1">
		<div class="title">
			<span class="std_title"><?php echo $this->__("Deal of the week ") ?></span><?php echo $this->__(" Lorem ipsum dolor sit amet consectetur adipiscing eget leo tellus luctus tellus aptent") ?>
		</div>					
		<div class="viewport">
			<div class="overview">
				<ul class="products-grid">				  
					<?php foreach ($_productCollection as $_product): ?> 
						<?php
							$name	=	$_helper->productAttribute($_product, $_product->getName(), 'name');
							if(strlen($name) >	20 ){
								$tam	=	substr($name, 0, 20);
								$plit	=	explode(" ", $tam);
								if(count($plit) > 1){
									$tam	=	array_slice($plit,0,count($plit)-1);
									$name	=	implode(" ", $tam).' ...';
								}
								else
									$name	=	$plit[0];
							}
						?>
						<li class="item">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h); ?>" width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							<?php Mage::helper('productlabels')->display($_product); ?>
							<div class="product-shop hover_quickshop" style="display:none" id="<?php echo 'order'.$_product->getEntityId(); ?>" >
								<div class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $name ?></a>
								</div>
							</div>							
						</li>					
					<?php endforeach ?>
						
				</ul>                         
			</div>
		</div>
		<div class="scrollbar" style="width: 675px;">
			<div class="track" style="width: 675px;">
				<div class="thumb" style="left: 0px; width: 101.20501999111505px;">
					<div class="end"></div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		jQuery('#scrollbar1 .products-grid li.item').slideUpDown({
			divHover : '.hover_quickshop'
		});
	</script>
	<script type="text/javascript">
		jQuery(document).ready(function($){		
			var li	=	jQuery("#scrollbar1 .viewport .overview ul.products-grid li.item");			
			if(li.length > 4) {
				if(window.document.documentMode == 7)
					w =	li.length*li[0].clientWidth;
				else
					w = li.length*li[0].getWidth();			
				jQuery('#scrollbar1 .viewport ul.products-grid').css({'width': w });
				jQuery('#scrollbar1').tinyscrollbar({ axis: 'x', scroll: true,size:'auto',sizethumb: "auto"});
			} else {
				jQuery('.scrollbar').hide();
			}
		});
	</script>
</div>
<?php endif ?>