<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
	
	$conf = new EM_Em0057settings_Em0057settings();	
	$w 	= $conf->get_widget_width();
	$h 	= $conf->get_widget_height();	
?>
<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div id="slideshow_featured_products" class="featured_products_content">
		<div class="slideshow-box">
			<div class="title"><?php echo $this->__("Featured Product") ?></div>			
			<ul class="products-grid jcarousel-skin-tango">					
				<?php foreach ($_productCollection as $_product): ?>  					
					<li class="item">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h); ?>" width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						<?php Mage::helper('productlabels')->display($_product); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<span class="sku"><?php echo $_product->getSku() ?></span>							
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>							
						<?php echo $this->getPriceHtml($_product, true) ?>
						
					</li>					
				<?php endforeach ?>					
			</ul>			
		</div>
	</div>
<?php endif ?>