<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php // Grid Mode ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>  
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
			<?php
				$name	=	$_helper->productAttribute($_product, $_product->getName(), 'name');
				if(strlen($name) >	20 ){
					$tam	=	substr($name, 0, 20);
					$plit	=	explode(" ", $tam);
					if(count($plit) > 1){
						$tam	=	array_slice($plit,0,count($plit)-1);
						$name	=	implode(" ", $tam).' ...';
					}
					else
						$name	=	$plit[0];
				}				
			?>
            <li class="items <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80); ?>" width="80" height="80" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="product_info">
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $name ?></a></h2>               
					<?php echo $this->getReviewsSummaryHtml($_product, 'short')?>
					<?php echo $this->getPriceHtml($_product, true) ?> 
				</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
<?php endif; ?>
