<?php if(Mage::getStoreConfig('blog/menu/show_recent_comment')):?>
<div class="block em_block-recent-comments">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recent Comments')?></span></strong>
    </div>
	<div class="block-content">
		<ol type="square">
			<?php $rcs = $this->getRecentComment(); //print_r($rcs);exit;; ?>
			<?php if($rcs->count() > 0 ) : ?>
				<?php $i = 0;foreach($rcs as $rc): ?>
      				<?php if($i = 0):?>
      					<?php $class="first";?>
      					<?php else:$class='';?>
      				<?php endif;?>
      					<li class="item recent-comment-item<?php echo $class;?>">
						   <a class="comment-title" href="<?php echo Mage::getUrl('blog').$rc->getUrl().'.html';?>" ><?php echo $rc->getTitlePost();?></a>
						   <?php $date = new DateTime($rc->getTime());?>
						   <small class="time-stamp"><?php echo $date->format('l, M j Y, h:iA'); ?></small>
      					   <div class="recent-comment-content">
      					       <?php echo $this->getTitleComment($rc->getCommentContent(),50); ?>
      					   </div>
						   <span class="comment-by"><?php echo $this->__('Commented by').' '?>
							   <span><?php echo $rc->getUsername()?></span>
						   </span>
      					</li>
			    <?php endforeach;?>						
			<?php else :  ?>
				<li><p class="empty"><?php echo $this->__('No recent comment') ?></p></li>
				<?php $i++;?>
			<?php endif; ?>	
		</ol>
	</div>
</div>
<?php endif;?>