<?php 
	$_products = $this->getProductCollection(); 
    
    $_helper = $this->helper('catalog/output');
	if(Mage::registry('current_category')){
    	  $_products->addUrlRewrite(Mage::registry('current_category')->getId());
    }
	
       
?>
<div class="featured-home-mobile">
<?php if ($_products->getSize()): ?>
<div class="widget em-widget-featured-products-grid">
    <div class="widget-title">
        <h2><?php echo $this->__('Feature Product'); ?></h2>
    </div>
    <div class="widget-products" id="slideshow_featured">
		<div class="featured_products">	
			<ul class="products-grid">
			<?php $i=0; foreach ($_products->getItems() as $_product): ?>
		 <?php 
					//$pId= $_product['entity_id']; 
					//$_product = Mage::getModel('catalog/product')->load($pId);
				?> 
				<li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
					<div class="product-shop">
						<div class="f-fix">
							<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
							 <!--span class="sku"><span></span><?php //echo $_product->getSku() ?></span-->
							 <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
						</div>
					</div>
				</li>
			<?php endforeach; ?>
			</ul>
		</div>
    </div>
</div>
<?php endif; ?>
</div>
