<?php 
	$_products = $this->getProductCollection(); 
    
    $_helper = $this->helper('catalog/output');
	if(Mage::registry('current_category')){
    	  $_products->addUrlRewrite(Mage::registry('current_category')->getId());
    }
          
    $limitproduct = $this->getLimitCount();    
    $size = $_products->getSize();
    
    if($limitproduct == "" || $limitproduct > $size){
        $limitproduct = $size;
    }
    
    $title = $this->getFrontendTitle();
    $desc  = $this->getFrontendDescription();
    $wrapclass = $this->getCustomClass();
    $w = $this->getThumbnailWidth();
    $h = $this->getThumbnailHeight();   
	$item_w = $this->getProductItemlWidth();
	$item_h = $this->getProductItemHeight();
?>

<div <?php if($wrapclass): ?>class="<?php echo $wrapclass;?>"<?php endif; ?>>
    <?php if($title): ?>      
        <div class="widget-title">
            <h2><span><?php echo $title; ?></span></h2>
        </div>
    <?php endif; ?>
    
    <?php if($desc):?>
        <p><?php echo $desc; ?></p>
    <?php endif ?>
        
    <?php if ($limitproduct): ?>
        <div class="widget em-widget-featured-products-list"> 
            <div class="widget-products">
                <ul class="products-list">
                    <?php $i=1; foreach ($_products->getItems() as $_product): ?>
                        <li style="width:<?php echo $item_w; ?>px; height:<?php echo $item_h;?>px" class="item<?php echo ($i == $limitproduct)?' last':''; ?>">
                            
                            <?php if ($this->ShowLabel()=='true'):?>
                                <!--show label product - label extension is required-->
                                <?php Mage::helper('productlabels')->display($_product);?>
                            <?php endif;?>
                            
                            <?php if ($this->ShowThumb()=='true'): ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w,$h) ?>" width="<?php echo $w; ?>" height="<?php echo $h ;?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                            <?php endif; ?>
                            
                            <div class="product-shop">
                                <div class="f-fix">
                                    <!--product name-->
                                    <?php if ($this->ShowProductName()=='true'):?>
                                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                                    <?php endif;?>
                                    
                                    <!--product description-->
                                    <?php if ($this->ShowDesc()=='true'):
                                        $desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
                                        if(strlen($desc)>80) { //dem ki tu chuoi $str, 80 la chieu dai muon quy dinh
                                            $strCutTitle = substr($desc, 0, 80); //cat 80 ki tu dau
                            				$desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
                       					}       
                                    ?>
                                        <p class="desc"><?php echo $desc; ?></p>
                                    <?php endif ;?>
                                    
                                    <!--product reviews-->
                                    <?php if ($this->ShowReview()=='true'):?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif ; ?>
                                    
                                    <!--product price-->
                                    <?php if ($this->ShowPrice()=='true'):?>
                                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
                                    <?php endif;?>
                                    
                                    <!--product add to cart-->
                                    <?php if ($this->ShowAddtoCart()=='true'):?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <!--product add to compare-wishlist-->
                                    <?php if($this->ShowAddto()=='true'):?>
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                            <?php endif; ?>
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                            <?php endif; ?>
                                        </ul>
                                    <?php endif; ?>
                                    
                                </div>
                            </div>
                        </li>
                        <?php $i++;?>
                        <?php if($i>$limitproduct) break;?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php else:?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php endif; ?>
</div>
