<?php
	$posts = $this->getPosts();
	$tool = $this->getToolbar()->setCollection($posts);
	$thumnailWidth = Mage::getStoreConfig('blog/info/thumbnail_width');
	$thumnailHeight = Mage::getStoreConfig('blog/info/thumbnail_height');
	$helper = Mage::helper('cms');
	$processor = $helper->getBlockTemplateProcessor();
	$catUrl = Mage::helper('blog')->getCatUrl($this->getRequest()->getParam('cat'));
?>
<?php if($posts->count() > 0):?>
<div class="em_post-items">
	<?php foreach ($posts as $post): ?>
            <?php $url = $catUrl.$post->getPostIdentifier().'.html';?>
	
	<div class="em_post-item">
		<?php $date = new DateTime($post->getPostOn());?>	
		<div class="blog_day"><span class="day"><?php echo $date->format('j'); ?></span><span class="month"><?php echo $date->format('M'); ?></span></div>
		<div class="post_list">
			<div class="post-title">
				<h2><a href="<?php echo $url; ?>" ><?php echo $post->getTitle();?></a></h2>	 
			</div>
		
			<div class="em_postlist-info">
						
				<div class="std">
					<?php if($post->getImage()):?>
									<a href="<?php echo $url;?>">
						<img src="<?php echo Mage::helper('blog')->resizeImage($post->getImage(),$thumnailWidth,$thumnailHeight,"em_blog/posts",'thumbnail');?>"/>
									</a>
					<?php endif;?>
				<?php echo $processor->filter($post->getPostIntro());?>
				</div>
			</div>
		
			<!--<div class="tags"><?php //echo $this->getTagsHtml($post) ?></div>-->
			<div class="post-footer">
				<span class="comment-count">
					<?php echo $this->getCommentByPost($post->getId())->count(); ?><a href="<?php echo $url; ?>" ><?php echo $this->__("Comments") ?></a>
				</span>
				<span class="separator">|</span>
				<span class="post-by">
					<?php echo Mage::helper('blog')->__('Posted by').' ';?><span><?php echo $post->getUsername(); ?></span>
				</span>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
</div>
<?php echo $tool->toHtml();?>

<?php else:?>
<p class="note-msg"><?php echo $this->__('There are no posts matching the selection.')?></p>
<?php endif;?>